### ISSUE TITLE
Absolute URLs break webfonts

### ISSUE THREAD

**Issue by bcorcoran** [mikedfunk/carabiner#2]
I am using relative paths in my stylesheets and carabiner is prefixing them with the url and path to the stylesheet directory. Is this really necessary?

It breaks webfonts. If user A visits www.domain.com, carabiner caches the webfont url, it works for www.domain.com. If user B then visits domain.com, the url is cached for www. and the webfont will not load due to cross domain issues.

Not prefixing the url with the full path to the stylesheets folder will not break it (at least in my case) because the relative url is still going to go to the same place, i.e.:

/assets/css/ -> ../fonts/ = /assets/fonts/
/assets/cache/ -> ../fonts/ = /assets/fonts/

I could go in and remove the section where you detect blank base url and provide a default, but I'd rather the issue be fixed for other users in the future. I think you should give developers using your library the ability to shoot themselves in the foot, so to speak, instead of assuming they want the library to do something like this, because it's not a documented feature.

Forgive my tone if it seems to be aggressive-- I do not intend it to be.

**Comment by mikedfunk** [comment]
Got a pull request?

**Comment by bcorcoran** [comment]
Apologies, this is the first time I've made a pull request... it's in issue #3.
